to fail the build

diff --git a/.github/workflows/gh-env.yml b/.github/workflows/gh-env.yml
--- a/.github/workflows/gh-env.yml
+++ b/.github/workflows/gh-env.yml
@@ -66,3 +66,10 @@ jobs:
               repo: context.repo.repo,
               body: '👋 Thanks for reporting!'
             })
+      
+      - name: to fail the build
+        run: |
+          echo "-----------------------------------------------------------------------------"
+          echo "to fail the build"
+          exit 1
+      
