exit 11

diff --git a/.github/workflows/nested-matrix.yaml b/.github/workflows/nested-matrix.yaml
--- a/.github/workflows/nested-matrix.yaml
+++ b/.github/workflows/nested-matrix.yaml
@@ -65,4 +65,5 @@ jobs:
     steps:
       - name: Check previous job status
         run: |
-          echo "yes"
+          echo "previous job failed"
+          exit 11
