exit  ${{ failure() }}

diff --git a/.github/workflows/nested-matrix.yaml b/.github/workflows/nested-matrix.yaml
--- a/.github/workflows/nested-matrix.yaml
+++ b/.github/workflows/nested-matrix.yaml
@@ -63,4 +63,6 @@ jobs:
     needs: [build]
     steps:
       - name: Check previous job status
-        run: exit $(failure())
+        run: |
+          echo "---[${{ failure() }}]---"
+          exit  ${{ failure() }}
